### ISSUE TITLE
primary_beam_correction.py : killed with astropy version 5.2.1

### ISSUE THREAD

**Issue by ifornax** [ska-sa/katsdpimageutils#15]
I try to run primary_beam_correction.py  on  a FITS created from Obit. However, there seems to be an issue with the function below, at p2w = image_wcs.pixel_to_world(col, row, 0, 0)[0]

def radial_offset(phase_center, image_wcs):
    """Compute radial offset of pixels from the phase centre in degrees.

    Parameters
    ----------
    phase_center : astropy.coordinations.SkyCoord
        phase center position
    image_wcs : astropy.wcs.wcs.WCS
        WCS keywords in the primary HDU
    """
    # Get pixel coordinates
    pixcrd = np.indices((image_wcs.array_shape[2], image_wcs.array_shape[3]))
    row = np.ravel(pixcrd[0]).squeeze()
    col = np.ravel(pixcrd[1]).squeeze()
    print(f"\n Get pixel coordinates Row, Col shape {row.shape, col.shape} \n")
    # Convert pixel coordinates to world coordinates
    p2w = image_wcs.pixel_to_world(col, row, 0, 0)[0]

    print(f"pix to world done {type(p2w)}")

    # Compute a separation vector between phase centre and source positions in degrees.
    separation_deg = p2w.separation(phase_center).deg

    return separation_deg

**Comment by mauch** [comment]
Oooh. Thanks @ifornax I'll take a look.

**Comment by ifornax** [comment]
We can close this ticket. I think it was a memory size issue.

**Comment by ifornax** [comment]
Works on machine with more RAM
